# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMVrdCFs2iZPWGgFRQ-_IGIdtehokqHs
"""

from flask import Flask, request, jsonify
import joblib
import os

from preprocessing import preprocess_text

app = Flask(__name__)

# =====================================================
# MAPPING ALGORITMA
# =====================================================

ALGO_MAP = {
    "Naive Bayes (Bernoulli)": "bnb",
    "Naive Bayes (Gaussian)": "gnb",
    "Naive Bayes (Multinomial)": "mnb",
    "SVM (Linear)": "svm_linear",
    "SVM (RBF)": "svm_rbf",
    "SVM (Sigmoid)": "svm_sigmoid",
    "SVM (Polynomial)": "svm_poly"
}

# =====================================================
# BUILD MODEL KEY
# =====================================================

def build_model_key(algo, split, feature_select):

    algo_code = ALGO_MAP[algo]

    # Naive Bayes → CountVectorizer
    if algo_code in ["bnb", "gnb", "mnb"]:

        model_name = (
            f"{algo_code}_{split}cv_{feature_select}"
        )

        vectorizer_name = (
            f"vectorizer{split}.pkl"
        )

        selector_name = (
            f"{feature_select}_selector{split}cv.pkl"
        )

    # SVM → TFIDF
    else:

        model_name = (
            f"{algo_code}_{split}tfidf_{feature_select}"
        )

        vectorizer_name = (
            f"tfidf{split}.pkl"
        )

        selector_name = (
            f"{feature_select}_selector{split}tfidf.pkl"
        )

    return (
        model_name,
        vectorizer_name,
        selector_name
    )


# =====================================================
# LOAD ASSET
# =====================================================

def load_assets(
    model_name,
    vectorizer_name,
    selector_name
):

    model_path = os.path.join(
        "models",
        f"{model_name}.pkl"
    )

    vectorizer_path = os.path.join(
        "vectorizers",
        vectorizer_name
    )

    selector_path = os.path.join(
        "selectors",
        selector_name
    )

    model = joblib.load(model_path)

    vectorizer = joblib.load(
        vectorizer_path
    )

    selector = joblib.load(
        selector_path
    )

    return (
        model,
        vectorizer,
        selector
    )


# =====================================================
# HOME
# =====================================================

@app.route("/")
def home():

    return jsonify(
        {
            "status": "running",
            "message": "Sentiment API Active"
        }
    )


# =====================================================
# PREDICT
# =====================================================

@app.route(
    "/predict",
    methods=["POST"]
)
def predict():

    try:

        data = request.json

        algo = data["algo"]
        split = data["split"]
        feature_select = data[
            "feature_select"
        ]
        text_input = data[
            "text_input"
        ]

        (
            model_name,
            vectorizer_name,
            selector_name
        ) = build_model_key(
            algo,
            split,
            feature_select
        )

        (
            model,
            vectorizer,
            selector
        ) = load_assets(
            model_name,
            vectorizer_name,
            selector_name
        )

        # ==========================
        # PREPROCESSING
        # ==========================

        processed_text = (
            preprocess_text(
                text_input
            )
        )

        # ==========================
        # VECTORIZE
        # ==========================

        X = vectorizer.transform(
            [processed_text]
        )

        # ==========================
        # FEATURE SELECTION
        # ==========================

        X = selector.transform(X)

        # ==========================
        # PREDICT
        # ==========================

        prediction = model.predict(X)[0]

        return jsonify(
            {
                "status": "success",
                "prediction": str(
                    prediction
                ),
                "model": model_name
            }
        )

    except Exception as e:

        return jsonify(
            {
                "status": "error",
                "message": str(e)
            }
        )


# =====================================================
# RUN
# =====================================================

if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )