# -*- coding: utf-8 -*-
"""preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IhMnMnz23VkXdmkEVsCLJE9San2iu4xx
"""

!pip install Sastrawi
import re
import pandas as pd
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.util import ngrams

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# ==========================
# LOAD KAMUS
# ==========================

kamus_data = pd.read_excel("kamuskatabaku.xlsx")

kamus_dict = dict(
    zip(
        kamus_data["tidak_baku"],
        kamus_data["kata_baku"]
    )
)

# ==========================
# STOPWORD
# ==========================

stop_words = set(
    stopwords.words("indonesian")
)

# ==========================
# STEMMER
# ==========================

factory = StemmerFactory()
stemmer = factory.create_stemmer()

# ==========================
# CLEANING
# ==========================

def remove_URL(text):

    return re.sub(
        r'https?://\S+|www\.\S+',
        '',
        text
    )


def remove_username(text):

    return re.sub(
        r'@[^\s]+',
        '',
        text
    )


def remove_hashtag(text):

    return re.sub(
        r'#\S+',
        '',
        text
    )


def remove_html(text):

    return re.sub(
        r'<.*?>',
        '',
        text
    )


def remove_html_entity(text):

    return re.sub(
        r'&[a-zA-Z]+;?',
        ' ',
        text
    )


def remove_emoji(text):

    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"
        u"\U0001F300-\U0001F5FF"
        u"\U0001F680-\U0001F6FF"
        u"\U0001F700-\U0001F77F"
        u"\U0001F780-\U0001F7FF"
        u"\U0001F800-\U0001F8FF"
        u"\U0001F900-\U0001F9FF"
        u"\U0001FA00-\U0001FA6F"
        u"\U0001FA70-\U0001FAFF"
        u"\U0001F004-\U0001F0CF"
        u"\U0001F1E0-\U0001F1FF"
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub('', text)


def remove_symbols(text):

    return re.sub(
        r'[^a-zA-Z0-9\s]',
        '',
        text
    )


def remove_numbers(text):

    return re.sub(
        r'\d',
        '',
        text
    )

# ==========================
# PREPROCESSING
# ==========================

def preprocess_text(text):

    # Cleaning

    text = remove_URL(text)

    text = remove_username(text)

    text = remove_hashtag(text)

    text = remove_html(text)

    text = remove_emoji(text)

    text = remove_html_entity(text)

    text = remove_symbols(text)

    text = remove_numbers(text)

    # Case Folding

    text = text.lower()

    # Tokenisasi

    tokens = text.split()

    # Normalisasi

    normalized = []

    for word in tokens:

        normalized.append(
            kamus_dict.get(word, word)
        )

    # Stopword

    filtered = []

    for word in normalized:

        if word not in stop_words:

            filtered.append(word)

    # Stemming

    stemmed = []

    for word in filtered:

        stemmed.append(
            stemmer.stem(word)
        )

    # Unigram + Bigram

    unigram = stemmed

    bigram = [
        "_".join(pair)
        for pair in ngrams(stemmed, 2)
    ]

    final_tokens = unigram + bigram

    # SAMAKAN DENGAN TRAINING

    return str(final_tokens)